### ISSUE TITLE
please help - fatal error

### ISSUE THREAD

**Issue by MikaTck** [Luccifer/BPM-Analyser#2]
Hi,
I appreciate you doing this, I've been searching everywhere for something that looks good to me.

Unfortunately my app crashes when I try to put it to action.
I also ran your sample project to check if I was doing something wrong and it still crashes in the same line of code. 
Could you help?

Thank you

 file - BMPAnalyzer.swift
 line 14 -       completion!(Superpowered().offlineAnalyze(url))

log:
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by Luccifer** [comment]
@MikaTck, thanks a lot for spotting the bug. To resolve it, please replace the code in BPMAnalizer.swift to:

`public func getBpmFrom(_ url: URL, completion: ((String) -> ())?) -> String {
        guard let bpmString: String = Superpowered().offlineAnalyze(url) else {return "Error analizing BPM"}
        if completion != nil {
            completion!(bpmString)
        }
        return Superpowered().offlineAnalyze(url)
    }`

Please tell me, if u have any other problems, appreciate any your question!
Also please inform me, if the problem resolved!

**Comment by MikaTck** [comment]
Hello Gleb.

Nice work!
Everything seems to be working well now, thank you very much for your fast
response.
I'll be sure to inform you if I find something unusual.

Best regards,
Mickael Domingues
