### ISSUE TITLE
On some songs the reported BPM rate is approximately twice as high as in online databases

### ISSUE THREAD

**Issue by o1exij** [Luccifer/BPM-Analyser#4]
Examples:

 IN EXTREMO 'Lebensbeichte'
REPORTED BPM: 178
https://songbpm.com/in-extremo-lebensbeichte?q=In%20Extremo%20-%20Lebensbeichte: 89

DEPECHE MODE 'A question of lust'
REPORTED BPM:  187.5
https://songbpm.com/depeche-mode-a-question-of-lust?q=depeche%20mode%20-%20a%20question%20of%20lust: 96

the other songs however are (almost) identical:
Archive - 'You make me feel'
REPORTED BPM: 167
https://songbpm.com/archive-you-make-me-feel?q=Archive%20-%20You%20make%20me%20feel: 167

**Comment by Luccifer** [comment]
Dunno, cause I just used lib for it in 'C', so swift and objective-C is just a bridge, you can find any information here: http://superpowered.com/

**Comment by o1exij** [comment]
I agree, you can't do anything about it. Nevertheless, thanks for your work!

**Comment by o1exij** [comment]
I found this ticket in super powered https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/issues/363 the recommendation is to set maximum bpm in offline analyzer to 160. Please update the lib according to this recomendation.

**Comment by Luccifer** [comment]
Ty! I will fix it in couple of days. If you have time - feel free to make PR

**Comment by Luccifer** [comment]
Lib Updated with the new fix @o1exij
