### ISSUE TITLE
Linker error for architecture arm64

### ISSUE THREAD

**Issue by danho322** [Luccifer/BPM-Analyser#6]
I'm trying to integrate BPMAnalyser into my project and am running into this roadblock. I'm having a hard time adding the Superpowered library correctly. I've added the Superpowered bridging header to my bridging header, and have added the libSuperpoweredAudioIOS.a to my linked frameworks, but still get the following error:
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Superpowered", referenced from:
      objc-class-ref in BMPAnalyzer.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Luccifer** [comment]
You should recompile that lib for all archs you need, cause I am not sure it was done by me.. You can download Superpower, compile it for all archs you need and than copy-paste .o lib in project

**Comment by danho322** [comment]
Do I then paste the .o lib into the DerivedData folder?

**Comment by Luccifer** [comment]
If you build all others for arm64, than yeah, why not

**Comment by danho322** [comment]
I just tried integrating from scratch again, and was successfully. It seemed to be the way I copied over the Superpower directory. Instead of adding and selecting the folder references, I selected the `Create Groups` option instead. That seemed to do the trick, although I don't fully understand it.

**Comment by Luccifer** [comment]
It's one of plenty possible solutions, glad you found a suitable one! Feel free to ask any questions!
