### ISSUE TITLE
Can't open this file Error Swift

### ISSUE THREAD

**Issue by ghost** [Luccifer/BPM-Analyser#8]
Hello Team, 
When I try to get bpm of the song by BPM Analyzer, they return error give below. Please check me  doing correct way to get bpm or not.

**Code Below:**

**First UseCase**
let dummySongURL = Bundle.main.url(forResource: "demo2", withExtension: "mp3")!
      `= BPMAnalyzer.init().getBpmFrom(dummySongURL) { (songBPM) in
       // error return: open error: Can't open this file.
     }` 

**Second UseCase**
let dummySongURL = "https://geekanddummy.com/wp-content/uploads/2014/02/central-locking-Ford-Mondeo-Mk-3.mp3"
      `= BPMAnalyzer.init().getBpmFrom(URL(string: urlss)!) { (songBPM) in
       //  open error: Use SuperpoweredAdvancedAudioPlayer::setTempFolder first.
     }` 

Can someone please explain to me how to get  this.
Any help would be greatly appreciated.
Thanks in advance.

**Comment by Luccifer** [comment]
Assuming use the right URL for file in First UseCase, have u checked, that file existed by this url? 
Try to check for file existence, cause sometimes people are missing to use absolute path and relative path to URL in FS. Try `Bundle.main.path(forResource: "example", ofType: "mp3")`

If we are trying to use Second case, I am not sure you can do it "on-air" from internet. Try to download it first, then make a right URL on FS for framework. I didn't test the web-grabbing songs either, so I will have a look in free time!
