### ISSUE TITLE
Not Return Correct BPM 

### ISSUE THREAD

**Issue by ghost** [Luccifer/BPM-Analyser#9]
Hello team, 
I am little bit confused because BPM-Analyser are not working properly. I am trying to check below songs Bpm through  BPM-Analyser  and return wrong bpm please check. 

**Song Name:-** Comfortably Numb by Pink Floyd 
**Song BPM:-**  64 BPM

**Reference Link:-** https://www.google.com/search?q=Comfortably+Numb+by+Pink+Floyd+bpm&oq=Comfortably+Numb+by+Pink+Floyd+bpm&aqs=chrome..69i57j0l7.3310j0j4&sourceid=chrome&ie=UTF-8 

**BPM Analyser** = 127 BPM

**Song Name:-** The End by The Beatles Song
**Song BPM:-**   123 BPM
**Reference Link:-** https://www.google.com/search?sxsrf=ALeKk02pCM3ZfW3c6TVpOJRCi4zqFCQHbA%3A1589551394007&ei=IqG-Xo0J_pDj4Q_SlY3gDQ&q=The+End+by+The+Beatles+Song+BPM&oq=The+End+by+The+Beatles+Song+BPM&gs_lcp=CgZwc3ktYWIQAzIICCEQFhAdEB46BAgAEEc6BAgjECc6AggAOgYIABAWEB5QxQVY-x9gliJoAHAAeACAAZ0BiAGhDJIBBDAuMTGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiNosSxhLbpAhV-yDgGHdJKA9wQ4dUDCAw&uact=5

**BPM Analyser** = 111 BPM

@Luccifer  @drougojrom  Please check this and reply me ASAP. Why BPM-Analyser return wrong or incorrect BPM.  

Looking forward to hear from you.
Thanks & Regards
Sham

**Comment by Luccifer** [comment]
Heya! 
As u can spot, the lib which is in use in this proj hasn't updated for about 3 years already. This proj - is only a wrapper, so SuperPowered already updated several times. 

If you want to make a research, try to give a chance to [Apple's one](https://developer.apple.com/documentation/mediaplayer/mpmediaitem/1621751-beatsperminute)

If you'll get a positive feedback of this research, u can ping us here, so we will update the wrapper with Apple's one inside.

Now we are fond of different researches far from iOS and mobile development, but u have my word, I ll keep a look after u will get any positive results from apple's and if they are correlated to yours references's ones -> we will figure that out!
